# Generated by Django 5.2.5 on 2025-08-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('linkPrecedence', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatededAt', models.DateTimeField(auto_now_add=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('linkedId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contact.contact')),
            ],
        ),
    ]
